name: Lint
on:
  pull_request:
    branches:
      - main
permissions:
  checks: read
  contents: read
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./server
        run: npm install

      - name: Server code format check
        working-directory: ./server
        run: npm run lint-check
